# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Expected peer group size for Peerless: will there be anything to compare against?

The funnel narrows, comparability narrows further, and recognition throws some
filings away. Nobody had multiplied those together, so the PRD asserted a
10-peer floor without knowing how often it would be cleared.

**What this covers, and what it does not.** For every comparable company in a
sample, treat it as the subject and count the other comparable companies that

  1. match it on `smaaForetak` (a comparability field, so a hard exclusion), and
  2. fall inside its size band on `sumDriftsinntekter`.

That is stages 1 and 2 of the funnel plus the size band. It does **not** apply
stage 3 segmentation beyond size, stage 4's business-model fingerprint, or stage
5 classification — the stages the screening report says do the real narrowing.
So every figure here is an **upper bound**, and the `/k` rows show what happens
if classification splits a code into k kinds of business (a reseller, a product
company and a consultancy all sit in 62.100).

Other assumptions, stated because they drive the answer:

* The sample of 100 per industry (seed 160) represents the population's size
  distribution. It is a random sample, so this is reasonable, but n=100 means
  the tails are thin and the non-`smaaForetak` subgroup is very thin indeed.
* A reconciled *column* means every figure in it is usable, so one 0.88 factor
  applies per company-year rather than one per field. If reconciliation were
  per-field, figures needing several OCR fields would be worse than this.
* Only the latest year is considered. Development over time needs the same
  company to reconcile across more years, which is strictly harder.

Run:  uv run analysis/peer_group_yield.py
"""

from __future__ import annotations

import csv
import statistics
from pathlib import Path

OUT = Path(__file__).parent / "output"

# Estimated comparable population per industry, from industry-screening.md
# ("Estimated comparable companies"), and the reconciliation rate from
# ocr-consistency.md / data-sources-brreg.md.
POPULATION = {"62100": 942, "69202": 789}
RECONCILE = 0.88
FLOOR = 10
BANDS = {"default": (0.5, 2.0), "loosened": (0.25, 4.0)}
# Plausible number of distinct business types sharing one code, for the
# classification-split bound. 62.100 is the heterogeneous case; 69.202 is the
# control, where 93 % describe core bookkeeping.
SPLIT = {"62100": 3, "69202": 2}


def load(code: str) -> list[dict]:
    path = OUT / f"sample-accounts-{code}.csv"
    with path.open(encoding="utf-8-sig", newline="") as fh:
        rows = list(csv.DictReader(fh, delimiter=";"))
    out = []
    for r in rows:
        if r["sammenlignbar"] != "True":
            continue
        try:
            revenue = int(r["sumDriftsinntekter"])
        except (ValueError, TypeError):
            continue
        if revenue <= 0:
            continue
        out.append({
            "orgnr": r["orgnr"],
            "revenue": revenue,
            "smaa": r["smaaForetak"] == "True",
        })
    return out


def peers_for(subj: dict, companies: list[dict], lo: float, hi: float) -> int:
    low, high = subj["revenue"] * lo, subj["revenue"] * hi
    return sum(
        1
        for c in companies
        if c["orgnr"] != subj["orgnr"]
        and c["smaa"] == subj["smaa"]
        and low <= c["revenue"] <= high
    )


def summarise(values: list[float]) -> dict:
    s = sorted(values)
    q = statistics.quantiles(s, n=4, method="inclusive") if len(s) > 1 else [s[0]] * 3
    return {
        "q1": q[0],
        "median": statistics.median(s),
        "q3": q[2],
        "min": s[0],
        "clears": sum(1 for v in s if v >= FLOOR) / len(s) * 100,
        "n": len(s),
    }


def row(label: str, st: dict) -> str:
    return (f"| {label} | {st['q1']:.0f} | {st['median']:.0f} | {st['q3']:.0f} "
            f"| {st['min']:.0f} | {st['clears']:.0f} % |")


def main() -> None:
    lines: list[str] = []
    w = lines.append
    w("# Expected peer group size — will there be anything to compare against?\n")
    w("Generated by `analysis/peer_group_yield.py`. **Read the script's docstring before "
      "quoting any of this.** These are upper bounds: stages 1 and 2 of the funnel plus the "
      "size band, with no fingerprint and no classification applied.\n")
    w(f"Size band on `sumDriftsinntekter`. Minimum group size {FLOOR} peers per key figure. "
      f"Reconciliation rate {RECONCILE:.0%} applied to every key figure needing a document.\n")

    for code in ("62100", "69202"):
        companies = load(code)
        pop, k = POPULATION[code], SPLIT[code]
        scale = pop / len(companies)
        smaa = [c for c in companies if c["smaa"]]
        non_smaa = [c for c in companies if not c["smaa"]]

        w(f"\n## {code[:2]}.{code[2:]}\n")
        w(f"- Comparable companies in sample: **{len(companies)}** of 100")
        w(f"- Estimated comparable population: **{pop}**")
        w(f"- `smaaForetak` true: **{len(smaa)}**, false: **{len(non_smaa)}** "
          f"(**{len(non_smaa) / len(companies):.0%}** of the comparable sample)")
        w(f"- Assumed classification split for the `/k` row: **k = {k}**\n")

        for band_name, (lo, hi) in BANDS.items():
            api = [peers_for(s, companies, lo, hi) * scale for s in companies]
            ocr = [v * RECONCILE for v in api]
            split = [v / k for v in ocr]
            w(f"\n### {band_name.capitalize()} band {lo:g}–{hi:g}×\n")
            w("| Stage reached | Q1 | Median | Q3 | Worst subject | Share clearing 10 |")
            w("|---|---|---|---|---|---|")
            w(row("Comparability + size band (API figures)", summarise(api)))
            w(row(f"…× {RECONCILE:.0%} reconciliation (document figures)", summarise(ocr)))
            w(row(f"…÷ {k} for classification (document figures)", summarise(split)))

        # The subgroup that actually fails.
        w("\n### The subgroup that fails\n")
        if non_smaa:
            sub_api = [peers_for(s, companies, 0.5, 2.0) * scale for s in non_smaa]
            st = summarise(sub_api)
            w(f"Subjects that are **not** `smaaForetak` (n = {st['n']} in sample, "
              f"about {len(non_smaa) * scale:.0f} in the population) can only be compared "
              f"against each other, because `smaaForetak` is a hard exclusion. "
              f"Default band, before reconciliation or classification: "
              f"median **{st['median']:.0f}**, worst **{st['min']:.0f}**, "
              f"**{st['clears']:.0f} %** clear the floor.")
        else:
            w("No non-`smaaForetak` company in this sample.")

    OUT.joinpath("peer-group-yield.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
